### ISSUE TITLE
ModuleNotFoundError: No module named 'rospkg'

### ISSUE THREAD

**Issue by mengxingshifen1218** [yanliang-wang/path_api_display#1]

**Comment by mengxingshifen1218** [comment]
seivl@seivl-Default-string:~/pnc_ws$ roslaunch get_path demo.launch
... logging to /home/seivl/.ros/log/ec7cdf76-aa9d-11ec-ae3b-08beac17f757/roslaunch-seivl-Default-string-5728.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

NODES
  /
    path_client (get_path/path_client.py)
    path_server (get_path/path_server.py)
    rviz (rviz/rviz)

auto-starting new master
process[master]: started with pid [5738]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to ec7cdf76-aa9d-11ec-ae3b-08beac17f757
process[rosout-1]: started with pid [5751]
started core service [/rosout]
process[rviz-2]: started with pid [5760]
process[path_client-3]: started with pid [5769]
process[path_server-4]: started with pid [5770]
  File "/home/seivl/pnc_ws/src/path_api_display/src/get_path/scripts/path_client.py", line 77
    except rospy.ServiceException, e:
                                 ^
SyntaxError: invalid syntax
[path_client-3] process has died [pid 5769, exit code 1, cmd /home/seivl/pnc_ws/src/path_api_display/src/get_path/scripts/path_client.py __name:=path_client __log:=/home/seivl/.ros/log/ec7cdf76-aa9d-11ec-ae3b-08beac17f757/path_client-3.log].
log file: /home/seivl/.ros/log/ec7cdf76-aa9d-11ec-ae3b-08beac17f757/path_client-3*.log
[ INFO] [1648035580.280108204]: rviz version 1.12.17
[ INFO] [1648035580.280149386]: compiled against Qt version 5.5.1
[ INFO] [1648035580.280161351]: compiled against OGRE version 1.9.0 (Ghadamon)
Traceback (most recent call last):
  File "/home/seivl/pnc_ws/src/path_api_display/src/get_path/scripts/path_server.py", line 5, in <module>
    import rospy
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/__init__.py", line 49, in <module>
    from .client import spin, myargv, init_node, \
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/client.py", line 52, in <module>
    import roslib
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslib/__init__.py", line 50, in <module>
    from roslib.launcher import load_manifest
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslib/launcher.py", line 42, in <module>
    import rospkg
ModuleNotFoundError: No module named 'rospkg'
[path_server-4] process has died [pid 5770, exit code 1, cmd /home/seivl/pnc_ws/src/path_api_display/src/get_path/scripts/path_server.py __name:=path_server __log:=/home/seivl/.ros/log/ec7cdf76-aa9d-11ec-ae3b-08beac17f757/path_server-4.log].
log file: /home/seivl/.ros/log/ec7cdf76-aa9d-11ec-ae3b-08beac17f757/path_server-4*.log
[ INFO] [1648035580.661357497]: Stereo is NOT SUPPORTED
[ INFO] [1648035580.661450183]: OpenGl version: 3 (GLSL 1.3).
[ERROR] [1648035580.707691425]: PluginlibFactory: The plugin for class 'rviz_plugins/AerialMapDisplay' failed to load.  Error: Failed to load library /home/seivl/pnc_ws/devel/lib//librviz_satellite.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version `Qt_5' not found (required by /home/seivl/pnc_ws/devel/lib//librviz_satellite.so))
[ERROR] [1648035580.708871658]: PluginlibFactory: The plugin for class 'rviz_plugins/AerialMapDisplay' failed to load.  Error: Failed to load library /home/seivl/pnc_ws/devel/lib//librviz_satellite.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version `Qt_5' not found (required by /home/seivl/pnc_ws/devel/lib//librviz_satellite.so))
[ERROR] [1648035580.709950252]: PluginlibFactory: The plugin for class 'rviz_plugins/AerialMapDisplay' failed to load.  Error: Failed to load library /home/seivl/pnc_ws/devel/lib//librviz_satellite.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version `Qt_5' not found (required by /home/seivl/pnc_ws/devel/lib//librviz_satellite.so))
^C[rviz-2] killing on exit
^C^C[rosout-1] killing on exit
^C[master] killing on exit
^C^Cshutting down processing monitor...
... shutting down processing monitor complete
done

hi 兄弟编译没有问题， 但是运行会报错，不知道你是否知道怎么解决

**Comment by yanliang-wang** [comment]
你的报错原因是这一行,`ModuleNotFoundError: No module named 'rospkg'`, python3默认是没有这个包的, 你要确保你终端使用的默认python是python2;

或者可以尝试安装python3的rospkag
```bash
sudo pip3 install rospkg
```

**Comment by WangCool1995** [comment]
ImportError: cannot import name 'wgs84_to_gcj02' from 'coordTransform_utils',这个怎么解决，大神？
